#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Stopping n2pdcim services...\n"
sudo systemctl stop n2pdcim
sudo systemctl disable n2pdcim

echo "=> Removing n2pdcim services...\n"
sudo rm -rf /usr/local/bin/n2pdcim.py
sudo rm -rf /usr/local/share/n2pdcim_venv
sudo rm -rf /etc/systemd/system/n2pdcim.service

echo "Success: n2pdcim service uninstalled!\n"
